name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform:
        - { packages: cmake ninja-build libsdl2-dev, flags: -G Ninja -DSDL_VERSION=SDL2 }
        - { packages: cmake ninja-build libsdl1.2-dev, flags: -G Ninja -DSDL_VERSION=SDL1 }

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install ${{matrix.platform.packages}}

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{matrix.platform.flags}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

  mingw-w64:
    runs-on: windows-latest

    defaults:
      run:
        shell: 'msys2 {0}'

    steps:
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        install: mingw-w64-i686-gcc mingw-w64-i686-cmake mingw-w64-i686-ninja mingw-w64-i686-SDL2

    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{matrix.platform.flags}}

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Package
      run: cmake --build build --config ${{env.BUILD_TYPE}} --target package

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: mousemaze-win32
        path: build/mousemaze-win32.zip

  riscos:
    runs-on: ubuntu-latest
    container: scummvm/dockerized-toolchains:riscos

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -Bbuild -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{matrix.platform.flags}} -DCMAKE_TOOLCHAIN_FILE=cmake/RISCOS.cmake

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Package
      run: cmake --build build --config ${{env.BUILD_TYPE}} --target package

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: mousemaze-riscos
        path: build/mousemaze-riscos.tar.gz
